// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKV3B0ED4_ik7AFC4Y-PiuCBzPMLYCTXQ',
    appId: '1:568214030239:web:2f229642791ac1d706dfaa',
    messagingSenderId: '568214030239',
    projectId: 'skin-diseases-93146',
    authDomain: 'skin-diseases-93146.firebaseapp.com',
    storageBucket: 'skin-diseases-93146.firebasestorage.app',
    measurementId: 'G-TN445XZ0PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkM9TrLeN-yYtkEbbEoq2Da4HgRB2cc8',
    appId: '1:568214030239:android:9050d1ff5ff5bc8506dfaa',
    messagingSenderId: '568214030239',
    projectId: 'skin-diseases-93146',
    storageBucket: 'skin-diseases-93146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRX1Pwwpyhg3rPbnSJDAlmZoWPeAu9Uc',
    appId: '1:568214030239:ios:3424d47b0496b0f406dfaa',
    messagingSenderId: '568214030239',
    projectId: 'skin-diseases-93146',
    storageBucket: 'skin-diseases-93146.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRX1Pwwpyhg3rPbnSJDAlmZoWPeAu9Uc',
    appId: '1:568214030239:ios:2caddb5e5aef337306dfaa',
    messagingSenderId: '568214030239',
    projectId: 'skin-diseases-93146',
    storageBucket: 'skin-diseases-93146.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
